name: Windows - build package and run tests
on: [push, pull_request] # This test is currently disabled until we can build Armadillo on Windows
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install Windows dependencies
      #   run: |
      #     cmake --version
      # - name: Install CPython from Anaconda # TODO: Need to update CMake? # TODO: See https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html
      #   run: |
      #     curl -XGET https://repo.anaconda.com/archive/Anaconda3-2021.11-Windows-x86_64.exe > Anaconda3-2021.11-Windows-x86_64.exe
      #     start /wait "" "Anaconda3-latest-Windows-x86_64.exe" /InstallationType=JustMe /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Anaconda3
      #     conda create -n "$p{{ matrix.python-version }}" python=${{ matrix.python-version }}
      #     conda activate p${{ matrix.python-version }}
      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Install Armadillo 10.7.5+
        run: |
          cd ~
          git clone https://gitlab.com/conradsnicta/armadillo-code.git
          cd armadillo-code
          cmake .
      - name: Install carma
        run: |
          cd ~
          git clone https://github.com/RUrlus/carma.git
          cd carma
          mkdir build
          cd build
          cmake -DCARMA_INSTALL_LIB=ON ..
          cmake --build . --config Release --target install
          cd ~
      - name: Install BanditPAM package
        run: |
          pip install -vvv -e .
        env:
          # The default compiler on the Github Ubuntu runners is gcc
          # Would need to make a respective include change for clang 
          CPLUS_INCLUDE_PATH: /usr/local/include/carma
      - name: Downloading data files for tests
        run: |
          mkdir -p data
          curl -XGET https://motiwari.com/banditpam_data/scRNA_1k.csv > data/scRNA_1k.csv
          curl -XGET https://motiwari.com/banditpam_data/scrna_reformat.csv.gz > data/scrna_reformat.csv.gz
          curl -XGET https://motiwari.com/banditpam_data/MNIST_100.csv > data/MNIST_100.csv
          curl -XGET https://motiwari.com/banditpam_data/MNIST_1k.csv > data/MNIST_1k.csv
          curl -XGET https://motiwari.com/banditpam_data/MNIST_10k.tar.gz > data/MNIST_10k.tar.gz
          tar -xzvf data/MNIST_10k.tar.gz -C data
          curl -XGET https://motiwari.com/banditpam_data/MNIST_70k.tar.gz > data/MNIST_70k.tar.gz
          tar -xzvf data/MNIST_70k.tar.gz -C data
      - name: Run smaller suite of test cases
        run : |
          pytest tests/test_smaller.py 
      # - name: Run larger suite of test cases
      #   run : |
      #     pytest tests/test_larger.py 
      # - name: Verify that the C++ executable compiles and runs
      #   run : |
      #     git clone https://github.com/ThrunGroup/BanditPAM
      #     cd BanditPAM
      #     mkdir build
      #     cd build
      #     cmake ..
      #     make
      #     src/BanditPAM -f ../data/MNIST_1k.csv -k 5